flask_app/movies/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user

from .. import movie_client
from ..forms import NewThreadForm, NewPostForm
from ..models import User, Review, Thread, Post
from ..utils import current_time

movies = Blueprint("movies", __name__)

@movies.route("/", methods=["GET", "POST"])
def index(): 
    return render_template("index.html")

"""
@movies.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    try:
        results = movie_client.search(query)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("movies.index"))

    return render_template("query.html", results=results)


@movies.route("/movies/<movie_id>", methods=["GET", "POST"])
def movie_detail(movie_id):
    try:
        result = movie_client.retrieve_movie_by_id(movie_id)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("movies.login"))

    form = MovieReviewForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        review = Review(
            commenter=current_user._get_current_object(),
            content=form.text.data,
            date=current_time(),
            imdb_id=movie_id,
            movie_title=result.title,
        )
        review.save()

        return redirect(request.path)

    reviews = Review.objects(imdb_id=movie_id)

    return render_template(
        "movie_detail.html", form=form, movie=result, reviews=reviews
    )
"""

@movies.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    reviews = Review.objects(commenter=user)

    return render_template("user_detail.html", username=username, reviews=reviews)


@movies.route("/action", methods=["GET", "POST"])
def action_board():

    form = NewThreadForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        thread = Thread(
            original=current_user._get_current_object(),
            topic= form.subject.data,
            description=form.content.data,
            thread_image=form.picture.data,
            genre="action"
        )

        thread.save()
        return redirect(request.path)

    threads = Thread.objects(genre="action")
    
    return render_template(
        "action.html", form=form, threads=threads
    )

@movies.route("/action/<topic>", methods=["GET", "POST"])
def action_thread(topic):
    form = NewPostForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        post = Post(
            commenter=current_user._get_current_object(),
            content=form.text.data,
            date=current_time(),
            topic=topic
        )

        post.save()
        return redirect(request.path)

    posts = Post.objects(topic=topic)
    
    return render_template(
        "action_thread.html", form=form, posts=posts, 
    )

@movies.route("/horror", methods=["GET", "POST"])
def horror_board():

    form = NewThreadForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        thread = Thread(
            original=current_user._get_current_object(),
            topic= form.subject.data,
            description=form.content.data,
            thread_image=form.picture.data,
            genre="horror"
        )

        thread.save()
        return redirect(request.path)

    threads = Thread.objects(genre="horror")
    
    return render_template(
        "horror.html", form=form, threads=threads
    )

@movies.route("/mystery", methods=["GET", "POST"])
def mystery_board():

    form = NewThreadForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        thread = Thread(
            original=current_user._get_current_object(),
            topic= form.subject.data,
            description=form.content.data,
            thread_image=form.picture.data,
            genre="mystery"
        )

        thread.save()
        return redirect(request.path)

    threads = Thread.objects(genre="mystery")
    
    return render_template(
        "mystery.html", form=form, threads=threads
    )

@movies.route("/romance", methods=["GET", "POST"])
def romance_board():

    form = NewThreadForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        thread = Thread(
            original=current_user._get_current_object(),
            topic= form.subject.data,
            description=form.content.data,
            thread_image=form.picture.data,
            genre="romance"
        )

        thread.save()
        return redirect(request.path)

    threads = Thread.objects(genre="romance")
    
    return render_template(
        "romance.html", form=form, threads=threads
    )

@movies.route("/documentary", methods=["GET", "POST"])
def documentary_board():

    form = NewThreadForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        thread = Thread(
            original=current_user._get_current_object(),
            topic= form.subject.data,
            description=form.content.data,
            thread_image=form.picture.data,
            genre="documentary"
        )

        thread.save()
        return redirect(request.path)

    threads = Thread.objects(genre="documentary")
    
    return render_template(
        "documentary.html", form=form, threads=threads
    )





flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.utils import secure_filename

from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdateProfilePicForm, UpdateUsernameForm
from ..models import User
import io
import base64


users = Blueprint("users", __name__)
def get_b64_img(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("movies.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()

        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("movies.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()
        print (User.objects)
        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("users.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("movies.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    username_form = UpdateUsernameForm()
    form2 = UpdateProfilePicForm()
    image = get_b64_img(current_user.username)
    current_user.modify(format_pic=image)

    if username_form.validate_on_submit():
        # current_user.username = username_form.username.data
        current_user.modify(username=username_form.username.data)
        current_user.save()
        return redirect(url_for("users.account"))

    if form2.validate_on_submit():
        image = form2.picture.data
        filename = secure_filename(image.filename)
        content_type = f'image/{filename[-3:]}'

        if current_user.profile_pic.get() is None:
            current_user.profile_pic.replace(image.stream, content_type=content_type)
            
        else:
            current_user.profile_pic.replace(image.stream, content_type=content_type)
            

        current_user.save()
        return redirect(url_for('users.account'))

    return render_template(
        "account.html",
        title="Account",
        username_form=username_form,
        form2=form2,
        image=image
    )

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row" style="display: inline-block; margin: 10px;">
    <div class="col" style="border-width: 5px; border-style: solid;">
        <h1>Welcome Back {{ current_user.username }}</h1>
    </div>
    <div class="col">
        {# Profile picture #}
        <img class="pic" src="data:image/png;base64,{{image}}" alt="image" style="width: 150px;height:150px; margin: 10px;">
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ username_form.csrf_token }}
            <div class="form-group">
                {{ username_form.username.label(class="form-control-label") }}
                {{ username_form.username(class="form-control form-control-lg") }}

                {% if username_form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ username_form.submit }}
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form2.csrf_token }}
            <div class="form-group">
              {{ form2.picture.label(class="form-control-label")}}
              {{ form2.picture(class="form-control form-control-lg") }}

              {% if form2.picture.errors %}
              <div class="alert alert-warning" role="alert">
                {% for error in form2.picture.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% endif %}
      
            </div>
            {{ form2.submit() }}
        </form>
    </div>
</div>
<h4 style="color: red">All Reports Made Against You:</h4>
</a>
{% endblock %}>

flask_app/templates/action.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div style="border-width: 5px; border-style: solid; margin-left: 485px; margin-top: 10px;">
        <div>
            <h2><em>Action</em></h2>
        </div>
    </div>
</div>

{# Threads #}
<div class="row">
<div class="col-md-12">
    <h1> Active Threads <small class="float-right">{{ threads|length }} threads total</small></h1>
    <ul class="media-list">
    {% for thread in threads %}
    <li class="media review-item">
        <img class="mr-3 comment-pic" src="{{thread.thread_image}}" alt="bad">
        <div class="media-body">
        <a href="{{ url_for('movies.action_thread', topic=thread.topic) }}">
            <strong>@{{ thread.topic }}</strong>
        </a>
        <p>
            {{ thread.description }}
        </p>
        </div>
    </li>
    {% endfor %}
    </ul>
</div>
</div>

{% if current_user.is_authenticated %}
{# Thread Creation Form #}
<h3>Create New Thread</h3>
<div class="row">
    <div class="col">
        <form method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.subject.label }}
            {{ form.subject(class="form-control") }}
            {% if form.subject.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in form.subject.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}

            {{ form.content.label }}
            {{ form.content(class="form-control") }}
            {% if form.content.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in form.content.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}

            {{ form.picture.label(class="form-control-label")}}
            {{ form.picture(class="form-control form-control-lg") }}

            {% if form.picture.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in form.picture.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit() }}
        </form>
    </div>
</div>
{% endif %}

{% endblock %}

flask_app/templates/action_thread.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div style="border-width: 5px; border-style: solid; margin-left: 485px; margin-top: 10px;">
        <div>
            <h2><em>Action Thread</em></h2>
        </div>
    </div>
</div>

{# Posts #}
<div class="row">
<div class="col-md-12">
    <h1>   <small class="float-right">{{ posts|length }} posts total</small></h1>
    <ul class="media-list">
    {% for post in posts %}
    <li class="media review-item">
        <div class="media-body">
        <a>
            <strong>@{{ post.commenter.username }}</strong>
        </a>
        <p>
            {{ post.content }}
        </p>
        </div>
    </li>
    {% endfor %}
    </ul>
</div>
</div>

{% if current_user.is_authenticated %}
{# Post Creation Form #}
<h3>Create New Post</h3>
<div class="row">
    <div class="col">
        <form method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.text.label }}
            {{ form.text(class="form-control") }}
            {% if form.text.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in form.text.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit() }}
        </form>
    </div>
</div>
{% endif %}

{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
     <link rel="shortcut icon" href="{{ url_for('static', filename='clapper.ico') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Movie Reviews</title>
    {% endif %}
</head>
<body style="background-color: rgb(17, 150, 83); color: white;">
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    
    <a class="navbar-brand" href="{{ url_for('movies.index') }}"><b>Home Page</b></a>
    
    
    <a class="navbar-brand" href="{{ url_for('movies.action_board') }}"> | Action &nbsp;/</a>
    <a class="navbar-brand" href="{{ url_for('movies.horror_board') }}"> Horror &nbsp;/</a>
    <a class="navbar-brand" href="{{ url_for('movies.mystery_board') }}"> Mystery &nbsp;/</a>
    <a class="navbar-brand" href="{{ url_for('movies.romance_board') }}"> Romance &nbsp;/</a>
    <a class="navbar-brand" href="{{ url_for('movies.documentary_board') }}"> Documentary &nbsp;|</a>
    
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            {% if current_user.is_authenticated %}
            <img class="propic" src="data:image/png;base64,{{current_user.format_pic}}" alt="No Image" style="width: 50px;height:50px;">
            <div class="dropdown">
                <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">User Settings<b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <li><a class="nav-link" href="{{ url_for('users.account') }}">Account</a></li>
                  <li><a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
                </ul>
              </div>
            {% else %}
            <div class="dropdown">
                <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">User Settings<b class="caret"></b></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <li><a class="nav-link" href="{{ url_for('users.login') }}">Login</a></li>
                  <li><a class="nav-link" href="{{ url_for('users.register') }}">Register</a></li>
                </ul>
              </div>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/horror.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <span style="border-width: 5px; border-style: solid; margin-left: 420; margin-top: 10px;">
        <div>
            <h2><em>Horror</em></h2>
        </div>
    </span>
</div>

{# Threads #}
<div class="row">
<div class="col-md-12">
    <h1> Active Threads <small class="float-right">{{ threads|length }} threads total</small></h1>
    <ul class="media-list">
    {% for thread in threads %}
    <li class="media review-item">
        <img class="mr-3 comment-pic" src="{{thread.thread_image}}" alt="bad">
        <div class="media-body">
        <a>
            <strong>@{{ thread.topic }}</strong>
        </a>
        <p>
            {{ thread.description }}
        </p>
        </div>
    </li>
    {% endfor %}
    </ul>
</div>
</div>

{% if current_user.is_authenticated %}
{# Thread Creation Form #}
<h3>Create New Thread</h3>
<div class="row">
    <div class="col">
        <form method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.subject.label }}
            {{ form.subject(class="form-control") }}
            {% if form.subject.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in form.subject.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}

            {{ form.content.label }}
            {{ form.content(class="form-control") }}
            {% if form.content.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in form.content.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}

            {{ form.picture.label(class="form-control-label")}}
            {{ form.picture(class="form-control form-control-lg") }}

            {% if form.picture.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in form.picture.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit() }}
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <span style="border-width: 5px; border-style: solid; margin-left: 420; margin-top: 10px; margin-bottom: 10px;">
        <div>
            <h2><em>Welcome to FlickPics</em></h2>
        </div>
    </span>
    <div class="container">
        <div>
            <h3>This is an imageboard for the discussion of different genres of movies (listed in the header of this website).
                Create an account and click on one of the boards to start posting! 
            </h3>
            <hX>Rules</hX>
            <ol>
                <li>No illegal content</li>
                <li>No spamming</li>
                <li>No mass/fake reporting</li>
            </ol>
        </div>
        <br>
        <h4></h4>
    </div>
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row" style="display: inline-block; margin: 10px;">
    <div class="col" style="border-width: 5px; border-style: solid;">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you <b>don't</b> have an account, then <a href="{{ url_for('users.register') }}">Register!</a>
    </div>
</div>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/movie_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}

{% if movie %}

{# Display card for the movie details #}
<div class="row">
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        {{ movie.title }} ({{ movie.year }})
      </div>
      <div class="card-body">
        <img src="{{ movie.poster_url }}" class="mr-3 movie" alt="alt text">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><b>Directed by:</b> {{ movie.director }}</li>
          <li class="list-group-item"><b>Actors:</b> {{ movie.actors }}</li>
          <li class="list-group-item"><b>Genres:</b> {{ movie.genres }}</li>
          <li class="list-group-item"><b>Awards:</b> {{ movie.awards }}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

{# Reviews #}
<div class="row">
  <div class="col-md-12">
    <h1> Reviews <small class="float-right">{{ reviews|length }} reviews</small></h1>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('movies.user_detail', username=review.commenter.username) }}">
            <strong>@{{ review.commenter.username }}</strong>
          </a>
          <p>
            {{ review.content }}
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}
{# Movie review submission form #}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endif %}
{% endblock content %}

flask_app/templates/mystery.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <span style="border-width: 5px; border-style: solid; margin-left: 420; margin-top: 10px;">
        <div>
            <h2><em>Mystery</em></h2>
        </div>
    </span>
</div>

{# Threads #}
<div class="row">
<div class="col-md-12">
    <h1> Active Threads <small class="float-right">{{ threads|length }} threads total</small></h1>
    <ul class="media-list">
    {% for thread in threads %}
    <li class="media review-item">
        <img class="mr-3 comment-pic" src="{{thread.thread_image}}" alt="bad">
        <div class="media-body">
        <a>
            <strong>@{{ thread.topic }}</strong>
        </a>
        <p>
            {{ thread.description }}
        </p>
        </div>
    </li>
    {% endfor %}
    </ul>
</div>
</div>

{% if current_user.is_authenticated %}
{# Thread Creation Form #}
<h3>Create New Thread</h3>
<div class="row">
    <div class="col">
        <form method="POST" action="" enctype="multipart/form-data">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.subject.label }}
            {{ form.subject(class="form-control") }}
            {% if form.subject.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in form.subject.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}

            {{ form.content.label }}
            {{ form.content(class="form-control") }}
            {% if form.content.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in form.content.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}

            {{ form.picture.label(class="form-control-label")}}
            {{ form.picture(class="form-control form-control-lg") }}

            {% if form.picture.errors %}
            <div class="alert alert-warning" role="alert">
            {% for error in form.picture.errors %}
            <span>{{ error }}</span>
            {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit() }}
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

flask_app/templates/query.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    {% for result in results %}
    <div class="media">
        <img src="{{ result.poster_url }}" class="mr-3 movie" alt="missing">
        <div class="media-body">
        <h5 class="mt-0"><a href="{{ url_for('movies.movie_detail', movie_id=result.imdb_id) }}">{{ result.title }}</a> ({{ result.year }})</h5>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <img class="propic" src="data:image/png;base64,{{image}}" alt="image">
    </div>
    <div class="col">
        <h2>{{ username }}'s Reviews</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        <h1> Reviews <small class="float-right">{{ reviews.count() }} reviews</small></h1>
        <ul class="media-list">
            {% for review in reviews %}
            <li class="media review-item">
                <div class="media-body">
                    <span class="float-right">
                        <small>{{ review.date }}</small>
                    </span>
                    <strong>For: <a href="{{ url_for('movies.movie_detail', movie_id=review.imdb_id) }}">
                            {{ review.movie_title }}
                        </a>
                    </strong>
                    <p>
                        {{ review.content }}
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}